## **NumPy Matrix Multiplication**

In [0]:
import numpy as np

In [3]:
m = np.array([[1,2],[3,4]])
m

array([[1, 2],
       [3, 4]])

In [5]:
n = m*2
n

array([[2, 4],
       [6, 8]])

In [6]:
m*n

array([[ 2,  8],
       [18, 32]])

In [8]:
x = np.multiply(m,n)
x

array([[ 2,  8],
       [18, 32]])

## **NumPy Matrix Product**


In [9]:
x = np.array([[1,2,3,4], [5,6,7,8]])
x

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
x.shape

(2, 4)

In [11]:
y = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
y

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [12]:
y.shape

(4, 4)

In [14]:
z = np.matmul(x,y)
z

array([[ 90, 100, 110, 120],
       [202, 228, 254, 280]])

In [15]:
z.shape

(2, 4)

## **NumPy's dot function**


In [16]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [18]:
np.dot(a,a)


array([[ 7, 10],
       [15, 22]])

In [19]:
a.dot(a,a)

array([[ 7, 10],
       [15, 22]])

In [20]:
np.matmul(a,a)

array([[199, 290],
       [435, 634]])

## **Transpose**


In [21]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [22]:
a.T

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

In [0]:
a_t = a.T

In [24]:
a_t[3][1] = 200
a_t

array([[  1,   5,   9,  13],
       [  2,   6,  10,  14],
       [  3,   7,  11,  15],
       [  4, 200,  12,  16]])

In [25]:
a

array([[  1,   2,   3,   4],
       [  5,   6,   7, 200],
       [  9,  10,  11,  12],
       [ 13,  14,  15,  16]])

In [26]:
input = np.array([[-0.25, 1 ,50 , 0.20]])
input

array([[-0.25,  1.  , 50.  ,  0.2 ]])

In [27]:
input.shape

(1, 4)

In [33]:
weights = np.array([[200,-25, 568, 2.66], [0.04, -0.003, 0.025, 0.009], [0.012, -0.045, 0.28, -0.067]])
weights

array([[ 2.00e+02, -2.50e+01,  5.68e+02,  2.66e+00],
       [ 4.00e-02, -3.00e-03,  2.50e-02,  9.00e-03],
       [ 1.20e-02, -4.50e-02,  2.80e-01, -6.70e-02]])

In [34]:
weights.shape

(3, 4)

In [36]:
np.matmul(input, weights.T)

array([[2.8325532e+04, 1.2388000e+00, 1.3938600e+01]])