In [0]:

import numpy as np

x = np.array([1,2,4,3,5])

In [6]:
print(x)
print(type(x))

[1 2 4 3 5]
<class 'numpy.ndarray'>


In [7]:
x.dtype

dtype('int64')

In [8]:
x.shape

(5,)

In [0]:
y = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [12]:
print(y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [13]:
y.shape

(4, 3)

In [14]:
y.size

12

In [15]:
print(x, x.dtype)

[1 2 4 3 5] int64


In [0]:
as