In [1]:
import numpy as np

In [10]:
x = np.full((4,8),8, dtype=int)

In [11]:
print(x.dtype)

int32


In [12]:
#Identity Matrix

In [15]:
x = np.eye(4,4)
print(x)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [16]:
#Diagonal Matrix

In [22]:
x = np.diag([10,20,30,40,50])
print(x)

[[10  0  0  0  0]
 [ 0 20  0  0  0]
 [ 0  0 30  0  0]
 [ 0  0  0 40  0]
 [ 0  0  0  0 50]]


In [25]:
x = np.linspace(0,10)
print(x)

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


In [29]:
x = np.arange(0,11)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10]


#Convert 1d array to 2D array(Reshape)

In [32]:
x = np.arange(20)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [35]:
#Reshape

In [40]:
x = np.reshape(x,(4,5))
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [42]:
x = np.reshape(x,(10,2))
print(x)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [43]:
#Random array

In [46]:
x = np.random.random((3,3))
print(x)

[[0.27720779 0.1356137  0.31827686]
 [0.86073683 0.7028202  0.0433285 ]
 [0.9740438  0.2149281  0.17329363]]


In [50]:
x = np.random.randint(10,15,(3,3))
print(x)

[[12 14 10]
 [12 10 14]
 [14 10 10]]


In [51]:
#normal distribution

In [55]:
x = np.random.normal(0,0.1, size = (100,100))
print(x)

[[ 0.02543126 -0.16246176  0.0749573  ...  0.08580252  0.1806352
  -0.06121214]
 [ 0.03971438 -0.03308797  0.09350568 ...  0.08573374 -0.02752731
  -0.09137613]
 [-0.03636548 -0.02867246 -0.00971562 ...  0.08461968 -0.01102738
   0.0402486 ]
 ...
 [-0.1654081   0.14356122 -0.08369757 ... -0.01068944 -0.00407409
  -0.02066069]
 [-0.06495128 -0.14842778 -0.05622175 ... -0.03258339  0.06565474
   0.10656953]
 [-0.08519628  0.05245716 -0.20153359 ... -0.07972602  0.15610671
   0.05884149]]


In [58]:
print("mean of x is", x.mean())
print("std of x is", x.std())
print("max of x is", x.max())
print("min of x is", x.min())
print("#positive of x is", (x > 0).sum())
print("#negative of x is", (x < 0).sum())




mean of x is -1.60082356826162e-05
std of x is 0.099035817487492
max of x is 0.3781616231945384
min of x is -0.3614426699836261
#positive of x is 4977
#negative of x is 5023


In [67]:
x = np.linspace(2,32,16).reshape(4,4)
print(x)

[[ 2.  4.  6.  8.]
 [10. 12. 14. 16.]
 [18. 20. 22. 24.]
 [26. 28. 30. 32.]]
